### ISSUE TITLE
Make env checker work for metaworld 

### ISSUE THREAD

**Issue by ottofabian** [ALRhub/fancy_gym#34]
Currently the environment checker for metaworld fails due to an missmatch between observation and observation space dtypes. That should be a relatively easy fix for the repo, but has not been solved yet. [Progress](https://github.com/rlworkgroup/metaworld/issues/374)

As soon as this works, we can enable the checker again in `make_metaworld`.

**Comment by D-o-d-o-x** [comment]
Fixed by the refactor.
